### ISSUE TITLE
SSL error on a Mac?

### ISSUE THREAD

**Issue by mrjcleaver** [northworld/google_calendar#79]
Hi,
  I get the SSL error - is this normal on a Mac? It makes me think something is wrong with my install.

 http://gist.github.com/fnichol/867550 seems to be targeted at Windows.

Thanks,
   Martin.
````
Copy the code that Google returned and paste it here:
(omitted)
/opt/chefdk/embedded/lib/ruby/2.1.0/net/http.rb:920:in `connect': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (Faraday::SSLError)
	from /opt/chefdk/embedded/lib/ruby/2.1.0/net/http.rb:920:in `block in connect'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/timeout.rb:76:in `timeout'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/net/http.rb:920:in `connect'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/net/http.rb:863:in `do_start'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/net/http.rb:852:in `start'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/net/http.rb:1369:in `request'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:82:in `perform_request'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:40:in `block in call'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:32:in `call'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/faraday-0.9.1/lib/faraday/request/url_encoded.rb:15:in `call'
	from /Volumes/Storage/martincleaver/.chefdk/gem/ruby/2.1.0/gems/signet-0.6.1/lib/signet/oauth_2/client.rb:957:in `fetch_access_token'
	from /Volumes/Storage/martincleaver/.chefdk/gem/ruby/2.1.0/gems/signet-0.6.1/lib/signet/oauth_2/client.rb:983:in `fetch_access_token!'
	from /Volumes/Storage/martincleaver/.chefdk/gem/ruby/2.1.0/gems/google_calendar-0.5/lib/google/connection.rb:133:in `get_new_access_token'
	from /Volumes/Storage/martincleaver/.chefdk/gem/ruby/2.1.0/gems/google_calendar-0.5/lib/google/connection.rb:94:in `login_with_auth_code'
	from /Volumes/Storage/martincleaver/.chefdk/gem/ruby/2.1.0/gems/google_calendar-0.5/lib/google/calendar.rb:73:in `login_with_auth_code'
	from gc.rb:24:in `<main>'
````

**Comment by szich** [comment]
Hi Martin, see issue #48

**Comment by mrjcleaver** [comment]
Ok - thanks. So it turned out to be some issue with ChefDK, the variant of Ruby I was using. https://github.com/chef/chef-dk/issues/376 gave me that hint.

Upgrading from v0.6.1 to v0.8.0 fixed it.
